add configurations file for eslint and prettier
GenesisAplicaciones/autofactura_frontend pull request #8
Opened 2023-06-01 23:25 UTC by AlbertoSanchez90

# Resumen

Se agregan los archivos de configuración para Eslint y Prettier

## Evidencia

No hay evidencia

2023-06-01 23:50 UTC, ericklugoj requested changes
se ve bien, haz pruebas creando nuevos componentes y rompiendo alguna de las reglas que agregaste y en teoria deberia salirte mensajes de warning y error por romper esas reglas.

checa lo de las lineas al final de los archivos (es necesario).

por ultimo checa lo de los scripts, dejalo como estaba para que solo analice la carpeta src, que es donde vive el codigo.

2023-06-01 23:50 UTC, ericklugoj commented on .eslintignore
> +env.d.ts
te falta agregar una linea en blanco al final, aplica para todos los archivos, siempre debe existir una linea en blanco hasta abajo.

2023-06-01 23:50 UTC, ericklugoj commented on .prettierignore
> +dist/
lo mismo aqui, agrega una linea en blanco al final

2023-06-01 23:50 UTC, ericklugoj commented on .prettierrc
> +  "bracketSpacing": true
por ahora me parece bien esta config, pero si en un futuro quisieran hacer cambios, estaria bien analizarlos y posiblemente agregar y/o quitar alguna de estas configuraciones

2023-06-01 23:50 UTC, ericklugoj commented on package.json
> +    "lint": "eslint . --ext .ts,.tsx",
esta linea regresala como estaba, si aceptas estos cambios nuevos va a analizar todo y solo necesitas escanear la carpeta src

2023-06-01 23:50 UTC, ericklugoj commented on package.json
> +    "lint": "eslint . --ext .ts,.tsx",
`"lint": "eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0"`

2023-06-02 00:03 UTC, AlbertoSanchez90 commented on package.json
> +    "lint": "eslint . --ext .ts,.tsx",
lo resolvi en 13d34c3ee605b5cb8bf09d0d6a3d94a540e416e6

2023-06-02 00:06 UTC, ericklugoj approved these changes
Chingon, lo hiciste todo perfecto 👌🏻

2023-06-02 00:30 UTC, EduardoRivas98 approved these changes

2023-06-02 00:32 UTC, merged